In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([1,2,3,4,5])
print(tensor_one_d)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
    [[1,2,0],
     [3,5,-1]],

    [[10,2,0],
     [1,0,2]],

    [[5,8,0],
     [2,7,0]],

    [[2,1,9],
     [4,-3,32]]
])

print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
print(tensor_three_d.shape)

(4, 2, 3)


In [ ]:
tensor_four_d = tf.constant([
  [
    [[1,2,0],
     [3,5,-1]],

    [[10,2,0],
     [1,0,2]],

    [[5,8,0],
     [2,7,0]],

    [[2,1,9],
     [4,-3,32]]
],

[
    [[1,2,0],
     [3,5,-1]],

    [[10,-2,0],
     [1,0,2]],

    [[5,-8,0],
     [2,-7,0]],

    [[2,-11,9],
     [4,-3,32]]
],

[
    [[1,20,0],
     [3,50,-1]],

    [[10,20,0],
     [1,0,2]],

    [[5,80,0],
     [2,70,0]],

    [[2,10,9],
     [4,-30,32]]
],
])

print(tensor_four_d)

tf.Tensor(
[[[[  1   2   0]
   [  3   5  -1]]

  [[ 10   2   0]
   [  1   0   2]]

  [[  5   8   0]
   [  2   7   0]]

  [[  2   1   9]
   [  4  -3  32]]]


 [[[  1   2   0]
   [  3   5  -1]]

  [[ 10  -2   0]
   [  1   0   2]]

  [[  5  -8   0]
   [  2  -7   0]]

  [[  2 -11   9]
   [  4  -3  32]]]


 [[[  1  20   0]
   [  3  50  -1]]

  [[ 10  20   0]
   [  1   0   2]]

  [[  5  80   0]
   [  2  70   0]]

  [[  2  10   9]
   [  4 -30  32]]]], shape=(3, 4, 2, 3), dtype=int32)


In [ ]:
tensor_bool = tf.constant([True, True, False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [ ]:
tensor_string = tf.constant("Hello World!")
print(tensor_string)

tf.Tensor(b'Hello World!', shape=(), dtype=string)


In [ ]:
tensor_string1 = tf.constant(["Hello World!", "Hi"])
print(tensor_string1)

tf.Tensor([b'Hello World!' b'Hi'], shape=(2,), dtype=string)


In [ ]:
np_array = np.array([1,2,3,4,5,6,7,8,9])
print(np_array)

[1 2 3 4 5 6 7 8 9]


In [ ]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int64)


In [ ]:
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns = None,
    batch_shape = None,
    dtype = tf.dtypes.float32,
    name = None
)

print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns = None,
    batch_shape = None,
    dtype = tf.dtypes.float32,
    name = None
)

print(3*eye_tensor)

tf.Tensor(
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]], shape=(3, 3), dtype=float32)


In [ ]:
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns = None,
    batch_shape = None,
    dtype = tf.dtypes.bool,
    name = None
)

print(eye_tensor)

tf.Tensor(
[[ True False False]
 [False  True False]
 [False False  True]], shape=(3, 3), dtype=bool)


In [ ]:
eye_tensor = tf.eye(
    num_rows = 5,
    num_columns = 3,
    batch_shape = None,
    dtype = tf.dtypes.float32,
    name = None
)

print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(5, 3), dtype=float32)


In [ ]:
eye_tensor = tf.eye(
    num_rows = 5,
    num_columns = 5,
    batch_shape = None,
    dtype = tf.dtypes.float32,
    name = None
)

print(eye_tensor)

tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)


In [ ]:
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns = None,
    batch_shape = [3,],
    dtype = tf.dtypes.float32,
    name = None
)

print(eye_tensor)

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(3, 3, 3), dtype=float32)


In [ ]:
eye_tensor = tf.eye(
    num_rows = 5,
    num_columns = None,
    batch_shape = [2,4,],
    dtype = tf.dtypes.float32,
    name = None
)

print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]], shape=(2, 4, 5, 5), dtype=float32)


In [ ]:
fill_tensor = tf.fill(
    [3,4], 5, name=None
)

print(fill_tensor)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [ ]:
fill_tensor = tf.fill(
    [1,3,4], 5, name=None
)

print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(1, 3, 4), dtype=int32)


In [ ]:
ones_tensor = tf.ones(
    [5,3,2],
    dtype= tf.dtypes.float32,
    name = None
)

print(ones_tensor)

tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(5, 3, 2), dtype=float32)


In [ ]:
ones_like_tensor = tf.ones_like(fill_tensor)
print(ones_like_tensor)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(1, 3, 4), dtype=int32)


In [ ]:
zeros_tensor = tf.zeros(
    [3,2],
    dtype= tf.dtypes.float32,
    name = None
)

print(zeros_tensor)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [ ]:
print(tensor_three_d.shape)

(4, 2, 3)


In [ ]:
print(tf.shape(tensor_three_d))

tf.Tensor([4 2 3], shape=(3,), dtype=int32)


In [ ]:
t = tf.constant([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
tf.rank(t)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
t = tf.constant([[1,1,1],[2,2,2]])
tf.rank(t)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
t = tf.constant([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
tf.size(t)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [ ]:
t = tf.constant([[1,1,1],[2,2,2]])
tf.size(t)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [ ]:
random_tensor = tf.random.normal(
    [3,2],
    mean = 0.0,
    stddev = 1.0,
    dtype = tf.dtypes.float32,
    seed = None,
    name = None

)

print(random_tensor)

tf.Tensor(
[[ 0.56501925  1.2351099 ]
 [-0.20574673  1.4968257 ]
 [-0.65784746  1.0039257 ]], shape=(3, 2), dtype=float32)


In [ ]:
random_tensor = tf.random.normal(
    [3,2],
    mean = 100.0,
    stddev = 1.0,
    dtype = tf.dtypes.float32,
    seed = None,
    name = None

)

print(random_tensor)

tf.Tensor(
[[ 99.447266  98.66759 ]
 [100.1599    98.32707 ]
 [101.50436  100.05067 ]], shape=(3, 2), dtype=float32)


In [ ]:
#randomly values around mean

**First Hour Finished**