# Second Week

In [9]:
import tensorflow as tf

In [10]:
tensor_two_d=tf.constant([[1,-2,0],
                          [3,5,100],
                          [1,5,6]],dtype=tf.float32)

In [11]:
tf.linalg.svd(tensor_two_d)

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([100.3663   ,   5.1059036,   1.2371687], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-7.4980810e-04, -3.7569830e-01,  9.2674178e-01],
        [ 9.9803799e-01, -5.8300879e-02, -2.2827482e-02],
        [ 6.2606096e-02,  9.2490643e-01,  3.7500489e-01]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.03044816,  0.07330841,  0.99684453],
        [ 0.0528536 ,  0.9957936 , -0.07484547],
        [ 0.998138  , -0.05496572, -0.02644547]], dtype=float32)>)

In [12]:
s , u , v = tf.linalg.svd(tensor_two_d)

print(s)

tf.Tensor([100.3663      5.1059036   1.2371687], shape=(3,), dtype=float32)


In [13]:
print(u)

tf.Tensor(
[[-7.4980810e-04 -3.7569830e-01  9.2674178e-01]
 [ 9.9803799e-01 -5.8300879e-02 -2.2827482e-02]
 [ 6.2606096e-02  9.2490643e-01  3.7500489e-01]], shape=(3, 3), dtype=float32)


In [14]:
print(v)

tf.Tensor(
[[ 0.03044816  0.07330841  0.99684453]
 [ 0.0528536   0.9957936  -0.07484547]
 [ 0.998138   -0.05496572 -0.02644547]], shape=(3, 3), dtype=float32)


In [15]:
import numpy as np

In [20]:
A=np.array([[2, 6, 5, 2],
            [2, -2, 2, 3],
            [1, 5, 4, 0]])

B=np.array([[2, 9, 0, 3, 0],
            [3, 6, 8, -2, 2],
            [1, 3, 5, 0, 1],
            [3, 0, 2, 0, 5]])

print(A.shape)
print(B.shape)

print("\n Matmul C = \n")
print(np.matmul(A,B),"\n")

(3, 4)
(4, 5)

 Matmul C = 

[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]] 



In [23]:
print ("Einsum C = \n")
print(np.einsum('ij,jk -> ik', A,B))
# i = row of A - j = column of A and row of B - k = column of B

Einsum C = 

[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]]


In [26]:
#elementwise
A=np.array([[2, 6, 5, 2],
            [2, -2, 2, 3],
            [1, 5, 4, 0]])

B=np.array([[2, 9, 0, 3],
            [3, 6, 8, -2],
            [1, 3, 5, 0]])

print("Hardamond C = \n")
print(A*B, "\n")

print ("Einsum C = \n")
print(np.einsum('ij,ij ->ij', A,B))

Hardamond C = 

[[  4  54   0   6]
 [  6 -12  16  -6]
 [  1  15  20   0]] 

Einsum C = 

[[  4  54   0   6]
 [  6 -12  16  -6]
 [  1  15  20   0]]


In [27]:
A = np.array([[2, 6, 5, 2],
              [2, -2, 2, 3],
              [1, 5, 4, 0]])

print("Transposed A = \n")
print(A.T, "\n")

Transposed A = 

[[ 2  2  1]
 [ 6 -2  5]
 [ 5  2  4]
 [ 2  3  0]] 



In [28]:
print("Einsum Transpoes A = \n")
print (np.einsum("ij -> ji" ,A))

Einsum Transpoes A = 

[[ 2  2  1]
 [ 6 -2  5]
 [ 5  2  4]
 [ 2  3  0]]


In [40]:
A = np.array([
                [[2, 6, 5, 2],
                 [2, -2, 2, 3],
                 [1, 5, 4, 0]],

                [[1, 3, 1, 22],
                 [0, 2, 2, 0],
                 [1, 5, 4, 1]]  ])

B = np.array([
              [[2, 9, 0, 3, 0],
               [3, 6, 8, -2, 2],
               [1, 3, 5, 0, 1],
               [3, 0, 2, 0, 5]],

              [[1, 0, 0, 3, 0],
               [3, 0, 4, -2, 2],
               [1, 0, 2, 0, 0],
               [3, 0, 1, 1, 0]]  ])

In [38]:
print(A.shape, B.shape)

(2, 3, 4) (2, 4, 5)


In [41]:
print("Batch Multiplication C = \n")
print(np.matmul(A,B), "\n")

Batch Multiplication C = 

[[[33 69 77 -6 27]
  [ 9 12  0 10 13]
  [21 51 60 -7 14]]

 [[77  0 36 19  6]
  [ 8  0 12 -4  4]
  [23  0 29 -6 10]]] 



In [42]:
print("Einsum C = \n")
print(np.einsum('bij,bjk -> bik', A,B))

Einsum C = 

[[[33 69 77 -6 27]
  [ 9 12  0 10 13]
  [21 51 60 -7 14]]

 [[77  0 36 19  6]
  [ 8  0 12 -4  4]
  [23  0 29 -6 10]]]


In [44]:
A = np.array([
                [[2, 6, 5, 2],
                 [2, -2, 2, 3],
                 [1, 5, 4, 0]],

                [[1, 3, 1, 22],
                 [0, 2, 2, 0],
                 [1, 5, 4, 1]] ])

In [45]:
print("Sum A = \n")
print(np.sum(A), "\n")

Sum A = 

72 



In [46]:
print ("Einsum A = \n")
print(np.einsum('bij ->', A))

Einsum A = 

72


In [49]:
A=np.array(
            [[2, 6, 5, 2],
             [2, -2, 2, 3],
             [1, 5, 4, 0]])

print("Axis 0 Sum A =  \n")
print(np.sum(A, axis = 0), "\n")

print("Einsum A = \n")
print(np.einsum('ij -> j', A), "\n")
print("-------------------- \n")

print("Axis 1 Sum A = \n")
print(np.sum(A, axis = 1), "\n")

print("Einsum A = \n")
print(np.einsum('ij -> i', A))

Axis 0 Sum A =  

[ 5  9 11  5] 

Einsum A = 

[ 5  9 11  5] 

-------------------- 

Axis 1 Sum A = 

[15  5 10] 

Einsum A = 

[15  5 10]


In [54]:
Q = np.random.randn(32, 64, 512)
K = np.random.randn(32, 128, 512)

In [55]:
np.einsum('bqm, bkm -> bqk', Q, K).shape

(32, 64, 128)

In [56]:
A = np.random.randn(2, 4, 4, 2)
B = np.random.randn(2, 4, 4, 1)

In [57]:
np.einsum("bcik, bcij -> bckj", B, A).shape

(2, 4, 1, 2)

In [60]:
np.matmul(np.transpose(B, (0, 1, 3, 2)), A).shape

(2, 4, 1, 2)

In [61]:
np.einsum("bcik, bcij -> bckj", B, A)

array([[[[-1.01594167,  0.84221121]],

        [[ 0.23553147,  3.3543091 ]],

        [[ 1.60388027, -0.71519461]],

        [[-1.82185733, -1.7761812 ]]],


       [[[-0.09728071, -0.35937421]],

        [[-2.14018125,  2.25213099]],

        [[ 1.2298231 ,  0.29852832]],

        [[ 0.63622659, -2.36621661]]]])

In [62]:
np.matmul(np.transpose(B, (0, 1, 3, 2)), A)

array([[[[-1.01594167,  0.84221121]],

        [[ 0.23553147,  3.3543091 ]],

        [[ 1.60388027, -0.71519461]],

        [[-1.82185733, -1.7761812 ]]],


       [[[-0.09728071, -0.35937421]],

        [[-2.14018125,  2.25213099]],

        [[ 1.2298231 ,  0.29852832]],

        [[ 0.63622659, -2.36621661]]]])

In [63]:
A = np.random.randn(2, 4, 6, 4, 2)
B = np.random.randn(2, 4, 6, 4, 1)

In [65]:
np.einsum("bcdik, bcdij -> bcdkj", B, A)

array([[[[[-1.22760871, -2.57735801]],

         [[-0.48806887,  3.20079249]],

         [[-1.50432574, -1.35293603]],

         [[-1.02125981, -0.63585535]],

         [[ 1.68645838,  0.27346567]],

         [[-0.15751007,  0.47074303]]],


        [[[-0.23604267, -2.64516651]],

         [[ 0.79483998, -2.09118609]],

         [[-5.16811836,  4.10644785]],

         [[-0.30516782,  0.86225903]],

         [[ 2.71047956,  1.4020438 ]],

         [[-2.57307734, -1.78142173]]],


        [[[-2.79698772, -2.10979996]],

         [[ 1.55632805,  3.64281408]],

         [[ 1.93651203, -0.32220071]],

         [[ 3.04838055,  0.45981145]],

         [[ 1.27824618, -2.57580147]],

         [[ 2.24501674,  1.30724665]]],


        [[[ 1.2817106 ,  1.52077812]],

         [[ 0.96029671,  1.43065052]],

         [[-1.06044848,  3.05049714]],

         [[-0.9550901 , -3.55919176]],

         [[ 1.29259535,  0.70769369]],

         [[-0.52049992, -0.47499491]]]],



       [[[[ 2.49092493,  2.855

In [66]:
np.einsum("bcdik, bcdij -> bcdkj", B, A).shape

(2, 4, 6, 1, 2)

In [67]:
np.matmul(np.transpose(B, (0, 1, 2, 4, 3)), A)

array([[[[[-1.22760871, -2.57735801]],

         [[-0.48806887,  3.20079249]],

         [[-1.50432574, -1.35293603]],

         [[-1.02125981, -0.63585535]],

         [[ 1.68645838,  0.27346567]],

         [[-0.15751007,  0.47074303]]],


        [[[-0.23604267, -2.64516651]],

         [[ 0.79483998, -2.09118609]],

         [[-5.16811836,  4.10644785]],

         [[-0.30516782,  0.86225903]],

         [[ 2.71047956,  1.4020438 ]],

         [[-2.57307734, -1.78142173]]],


        [[[-2.79698772, -2.10979996]],

         [[ 1.55632805,  3.64281408]],

         [[ 1.93651203, -0.32220071]],

         [[ 3.04838055,  0.45981145]],

         [[ 1.27824618, -2.57580147]],

         [[ 2.24501674,  1.30724665]]],


        [[[ 1.2817106 ,  1.52077812]],

         [[ 0.96029671,  1.43065052]],

         [[-1.06044848,  3.05049714]],

         [[-0.9550901 , -3.55919176]],

         [[ 1.29259535,  0.70769369]],

         [[-0.52049992, -0.47499491]]]],



       [[[[ 2.49092493,  2.855

In [68]:
np.matmul(np.transpose(B, (0, 1, 2, 4, 3)), A).shape

(2, 4, 6, 1, 2)

In [71]:
tensor_three_d=tf.constant([[[1, 2, 0],
                             [3, 5, -1]],

                             [[10, 2, 0],
                             [1, 0, 2]],

                             [[5, 8, 0],
                             [2, 7, 0]],

                             [[2, 1, 9],
                             [4, -3, 32]]])
print(tensor_three_d.shape)

(4, 2, 3)


In [73]:
print(tf.expand_dims(tensor_three_d, axis = 0).shape)

(1, 4, 2, 3)


In [76]:
x = tf.constant([2, 3, 4, 5])
print(x.shape)
print(tf.expand_dims(x, axis = 0).shape)

(4,)
(1, 4)


In [77]:
x = tf.constant([[2, 3, 4, 5]])
print(x.shape)
print(tf.expand_dims(x, axis = 0).shape)

(1, 4)
(1, 1, 4)


In [78]:
x = tf.constant([[[2, 3, 4, 5]]])
print(x.shape)
print(tf.expand_dims(x, axis = 0).shape)

(1, 1, 4)
(1, 1, 1, 4)


In [80]:
print(tensor_three_d.shape)
print(tf.expand_dims(tensor_three_d, axis = 3).shape)

(4, 2, 3)
(4, 2, 3, 1)


In [81]:
x = tf.constant([[[2, 3, 4, 5]]])
print(x.shape)
x_expanded = tf.expand_dims(x, axis = 0)
print(x_expanded)

(1, 1, 4)
tf.Tensor([[[[2 3 4 5]]]], shape=(1, 1, 1, 4), dtype=int32)


In [82]:
x_squeezed = tf.squeeze(x_expanded , axis =0 )
print(x_squeezed)

tf.Tensor([[[2 3 4 5]]], shape=(1, 1, 4), dtype=int32)


In [85]:
x_squeezed = tf.squeeze(x_expanded , axis =0 )
for i in range(2):
    x_squeezed = tf.squeeze(x_squeezed, axis = 0)

print(x_squeezed)

tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)


In [87]:
print(tensor_three_d.shape)
x_exp = tf.expand_dims(tensor_three_d, axis = 3)
print(x_exp.shape)
print(tf.squeeze(x_exp, axis = 3).shape)
print(tf.reshape(x_exp, [4,2,3]).shape)

(4, 2, 3)
(4, 2, 3, 1)
(4, 2, 3)
(4, 2, 3)


In [88]:
print(tf.squeeze(x_exp, axis = 3))
print(tf.reshape(x_exp, [4,2,3]))

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)
tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [89]:
x_reshape = tf.constant([[3, 5, 6, 6],
                         [4, 6, -1, 2]])

tf.reshape(x_reshape, [8])

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([ 3,  5,  6,  6,  4,  6, -1,  2], dtype=int32)>

In [90]:
tf.reshape(x_reshape, [2, 4])

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 3,  5,  6,  6],
       [ 4,  6, -1,  2]], dtype=int32)>

In [91]:
tf.reshape(x_reshape, [4, 2])

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 3,  5],
       [ 6,  6],
       [ 4,  6],
       [-1,  2]], dtype=int32)>

In [92]:
tf.transpose(x_reshape)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 5,  6],
       [ 6, -1],
       [ 6,  2]], dtype=int32)>

In [93]:
tf.reshape(x_reshape, [4, 2, 1])

<tf.Tensor: shape=(4, 2, 1), dtype=int32, numpy=
array([[[ 3],
        [ 5]],

       [[ 6],
        [ 6]],

       [[ 4],
        [ 6]],

       [[-1],
        [ 2]]], dtype=int32)>

In [94]:
tf.reshape(x_reshape, [4, -1])

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 3,  5],
       [ 6,  6],
       [ 4,  6],
       [-1,  2]], dtype=int32)>

In [95]:
t1 = [[1, 2, 3],
      [4, 5, 6]]

t2 = [[7, 8, 9],
      [10, 11, 12]]

tf.concat([t1 , t2], axis = 0)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [96]:
print(tf.constant(t1).shape)
print(tf.constant(t2).shape)

(2, 3)
(2, 3)


In [97]:
tf.concat([t1 , t2], axis = 1)

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]], dtype=int32)>

In [98]:
t1 = [[[1, 2, 3],
       [4, 5, 6]]]

t2 = [[[7, 8, 9],
       [10, 11, 12]]]

tf.concat([t1 , t2], axis = 0)

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [99]:
tf.concat([t1 , t2], axis = 1)

<tf.Tensor: shape=(1, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [104]:
tf.stack([t1, t2], axis = 0)

<tf.Tensor: shape=(2, 1, 2, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6]]],


       [[[ 7,  8,  9],
         [10, 11, 12]]]], dtype=int32)>

In [103]:
tf.stack([t1, t2, t1], axis = 0)

<tf.Tensor: shape=(3, 1, 2, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6]]],


       [[[ 7,  8,  9],
         [10, 11, 12]]],


       [[[ 1,  2,  3],
         [ 4,  5,  6]]]], dtype=int32)>

In [105]:
tf.concat([tf.expand_dims(t, axis = 0) for t in[t1, t2]], axis = 0)

<tf.Tensor: shape=(2, 1, 2, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6]]],


       [[[ 7,  8,  9],
         [10, 11, 12]]]], dtype=int32)>

In [106]:
t = tf.constant([[1, 2, 3], [4, 5, 6]])
paddings = tf.constant ([[1, 1], [2, 2]])

In [107]:
tf.pad(t, paddings, "CONSTANT", constant_values = 3)

<tf.Tensor: shape=(4, 7), dtype=int32, numpy=
array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 1, 2, 3, 3, 3],
       [3, 3, 4, 5, 6, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]], dtype=int32)>

In [108]:
tf.pad(t, paddings, "CONSTANT", constant_values = 0)

<tf.Tensor: shape=(4, 7), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 0, 0],
       [0, 0, 4, 5, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

In [118]:
params = tf.constant(['p0', 'p1', 'p2', 'p3', 'p4', 'p5'])
print(params.shape)
params[0:3+1]

(6,)


<tf.Tensor: shape=(4,), dtype=string, numpy=array([b'p0', b'p1', b'p2', b'p3'], dtype=object)>

In [110]:
params[1:3+1]

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [111]:
tf.gather(params, [1, 2, 3])


<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [112]:
tf.gather(params, tf.range(1, 4))

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [113]:
tf.gather(params, [0,5,3])

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p0', b'p5', b'p3'], dtype=object)>

In [119]:
params = tf.constant([

                       [0, 1.0, 2.0],
                       [10.0, 11.0, 12.0],
                       [20.0, 21.0, 22.0],
                       [30.0, 31.0, 32.0] ])

print(params.shape)
tf.gather(params, [0])

(4, 3)


<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0., 1., 2.]], dtype=float32)>

In [120]:
tf.gather(params, [0], axis = 0)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0., 1., 2.]], dtype=float32)>

In [126]:
params = tf.constant([[[0, 1.0, 2.0],
                       [10.0, 11.0, 12.0],
                       [20.0, 21.0, 22.0],
                       [30.0, 31.0, 32.0]]])

print(params.shape)
tf.gather(params, [2, 0], axis = 1)

(1, 4, 3)


<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[20., 21., 22.],
        [ 0.,  1.,  2.]]], dtype=float32)>

In [127]:
params = tf.constant([[[0, 1.0, 2.0],
                       [10.0, 11.0, 12.0],
                       [20.0, 21.0, 22.0],
                       [30.0, 31.0, 32.0]],

                      [[3, 1, 21],
                       [1, 3, 88],
                       [0, 5, 55],
                       [0, 2, 30]]])

print(params.shape)
tf.gather(params, [2, 0], axis = 1)

(2, 4, 3)


<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[20., 21., 22.],
        [ 0.,  1.,  2.]],

       [[ 0.,  5., 55.],
        [ 3.,  1., 21.]]], dtype=float32)>

In [129]:
indices = [[0],
           [1]]

params = [['a', 'b'],
          ['c', 'd']]

tf.gather_nd(params, indices)

<tf.Tensor: shape=(2, 2), dtype=string, numpy=
array([[b'a', b'b'],
       [b'c', b'd']], dtype=object)>

In [130]:
indices = [[0]]

params = [['a', 'b'],
          ['c', 'd']]

tf.gather_nd(params, indices)

<tf.Tensor: shape=(1, 2), dtype=string, numpy=array([[b'a', b'b']], dtype=object)>

In [131]:
indices = [[2]]

params = [['a', 'b'],
          ['c', 'd'],
          ['e', 'f']]

tf.gather_nd(params, indices)

<tf.Tensor: shape=(1, 2), dtype=string, numpy=array([[b'e', b'f']], dtype=object)>

In [132]:
indices = [[2, 1]]

params = [['a', 'b'],
          ['c', 'd'],
          ['e', 'f']]

tf.gather_nd(params, indices)

#row 2, column 1

<tf.Tensor: shape=(1,), dtype=string, numpy=array([b'f'], dtype=object)>

In [133]:
tf.gather(params, indices)


<tf.Tensor: shape=(1, 2, 2), dtype=string, numpy=
array([[[b'e', b'f'],
        [b'c', b'd']]], dtype=object)>

In [135]:
indices = [[0, 1, 0], [1, 0, 1]]


params = [[['a0', 'b0'],
           ['c0', 'd0']],

           [['a1', 'b1'],
            ['c1', 'd1']]]

tf.gather_nd(params, indices)

<tf.Tensor: shape=(1, 2), dtype=string, numpy=array([[b'c0', b'b1']], dtype=object)>

In [137]:
indices = [[[0, 1],
            [1, 0]],

           [[0, 0],
            [1, 1]]]


params = [[['a0', 'b0'],
           ['c0', 'd0']],

           [['a1', 'b1'],
            ['c1', 'd1']]]

tf.gather_nd(params, indices)

<tf.Tensor: shape=(2, 2, 2), dtype=string, numpy=
array([[[b'c0', b'd0'],
        [b'a1', b'b1']],

       [[b'a0', b'b0'],
        [b'c1', b'd1']]], dtype=object)>

In [138]:
tf.gather_nd(params, indices, batch_dims = 0)

<tf.Tensor: shape=(2, 2, 2), dtype=string, numpy=
array([[[b'c0', b'd0'],
        [b'a1', b'b1']],

       [[b'a0', b'b0'],
        [b'c1', b'd1']]], dtype=object)>

In [139]:
tf.gather_nd(params, indices, batch_dims = 1)

<tf.Tensor: shape=(2, 2), dtype=string, numpy=
array([[b'b0', b'c0'],
       [b'a1', b'd1']], dtype=object)>

In [144]:
tensor_two_d = tf.constant([[1, 2, 0],
                            [3, 5, -1],
                            [1, 5, 6],
                            [2, 3, 8]])

print(tensor_two_d.shape)

(4, 3)


In [146]:
tensor_two_d = [[1,2,0],
                [3,],
                [1,5,6,5,6],
                [2,3]]

tensor_ragged = tf.ragged.constant(tensor_two_d)
print(tensor_ragged)

<tf.RaggedTensor [[1, 2, 0], [3], [1, 5, 6, 5, 6], [2, 3]]>


In [147]:
print(tf.RaggedTensor.from_row_lengths(
      values=[3, 1, 4, 1, 5, 9, 2, 6],
      row_lengths=[4, 0, 3, 1, 0]))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [149]:
tensor_sparse = tf.sparse.SparseTensor(

    indices=[[1,1],[3,4]], values = [11,56], dense_shape = [5,6]
)

In [150]:
print(tensor_sparse)

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 56], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))


In [151]:
tf.sparse.to_dense(tensor_sparse)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 56,  0],
       [ 0,  0,  0,  0,  0,  0]], dtype=int32)>

In [152]:
tensor_string = tf.constant(['hello', 'i am', 'a string'])
print(tensor_string)

tf.Tensor([b'hello' b'i am' b'a string'], shape=(3,), dtype=string)


In [154]:
tf.strings.join(tensor_string, separator ="")

<tf.Tensor: shape=(), dtype=string, numpy=b'helloi ama string'>

In [155]:
tf.strings.join(tensor_string, separator =" ")

<tf.Tensor: shape=(), dtype=string, numpy=b'hello i am a string'>

In [156]:
tf.strings.join(tensor_string, separator ="+")

<tf.Tensor: shape=(), dtype=string, numpy=b'hello+i am+a string'>

In [157]:
tf.constant([1, 2])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [171]:
x_var = tf.Variable(x)
print(x_var)
print(x_var.device)

<tf.Variable 'Variable:0' shape=(1, 1, 4) dtype=int32, numpy=array([[[2, 3, 4, 5]]], dtype=int32)>
/job:localhost/replica:0/task:0/device:CPU:0


In [172]:
x_var = tf.Variable(x, name = 'var1')
print(x_var)

<tf.Variable 'var1:0' shape=(1, 1, 4) dtype=int32, numpy=array([[[2, 3, 4, 5]]], dtype=int32)>


In [169]:
with tf.device('GPU:0'):
  x_var = tf.Variable(0.2)

with tf.device('CPU:0'):
  x_tensor = tf.constant(0.2)

print(x_var.device)
print(x_tensor.device)

/job:localhost/replica:0/task:0/device:CPU:0
/job:localhost/replica:0/task:0/device:CPU:0


In [166]:
with tf.device('CPU:0'):
  x_1 = tf.constant([1, 3, 4])
  x_2 = tf.constant([1])

with tf.device('GPU:0'):
  x_3 = x_1 + x_2

print(x_1, x_1.device)
print(x_2, x_2.device)
print(x_3, x_3.device)

tf.Tensor([1 3 4], shape=(3,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([1], shape=(1,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([2 4 5], shape=(3,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
