# First Week - Second part

In [2]:
import tensorflow as tf
import numpy as np

In [ ]:
random_tensor = tf.random .uniform(

    [5, ],
    minval=0,
    maxval=100,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None,

    )
print(random_tensor)

tf.Tensor([68.64908  34.87818  22.33665  54.825867 22.925795], shape=(5,), dtype=float32)


In [ ]:
random_tensor = tf.random .uniform(

    [5, ],
    minval=0,
    maxval=1000,
    dtype=tf.dtypes.int32,
    seed=None,
    name=None,

    )
print(random_tensor)

tf.Tensor([902 161 570 264 828], shape=(5,), dtype=int32)


In [ ]:
random_tensor = tf.random .uniform(

    [5,5],
    minval=0,
    maxval=1000,
    dtype=tf.dtypes.int32,
    seed=None,
    name=None,

    )
print(random_tensor)

tf.Tensor(
[[993 950 131 616 853]
 [875 186 851 805  79]
 [268 473 288 439 221]
 [575 557 968 628 596]
 [427 492 974 909 860]], shape=(5, 5), dtype=int32)


In [ ]:
tf.random.set_seed(5)
print (tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print (tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print (tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print (tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [ ]:
tf.random.set_seed(5)
print (tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print (tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print (tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print (tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=1))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([4 1 3], shape=(3,), dtype=int32)


In [ ]:
#every time u run this, ull get different result

print (tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print (tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print (tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print (tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))

tf.Tensor([4 0 4], shape=(3,), dtype=int32)
tf.Tensor([1 4 3], shape=(3,), dtype=int32)
tf.Tensor([0 0 0], shape=(3,), dtype=int32)
tf.Tensor([3 0 0], shape=(3,), dtype=int32)


In [ ]:
tensor_indexed = tf.constant([3,6,2,4,6,66,7])
print (tensor_indexed)

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)


In [ ]:
print (tensor_indexed[0 : 4])
print (tensor_indexed[1 : 5+1])
#skip 2
print (tensor_indexed[1 : 6 : 2])
#means from 0 to 4
print (tensor_indexed[:4])
#means 3 to end
print (tensor_indexed[3:])

tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([ 6  2  4  6 66], shape=(5,), dtype=int32)
tf.Tensor([ 6  4 66], shape=(3,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([ 4  6 66  7], shape=(4,), dtype=int32)


In [ ]:
print (tensor_indexed[3:-1])
print (tensor_indexed[3:-2])

tf.Tensor([ 4  6 66], shape=(3,), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)


In [ ]:
tf.range(2,6)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5], dtype=int32)>

In [ ]:
tensor_two_d = tf.constant([

        [1,2,0],
        [3,5,-1],
        [1,5,6],
        [2,3,8]

        ])
#(rows,columns)
print(tensor_two_d[0:3,0:2])

tf.Tensor(
[[1 2]
 [3 5]
 [1 5]], shape=(3, 2), dtype=int32)


In [ ]:
print(tensor_two_d[0:3,:])

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]], shape=(3, 3), dtype=int32)


In [ ]:
print(tensor_two_d[3,:])

tf.Tensor([2 3 8], shape=(3,), dtype=int32)


In [ ]:
print(tensor_two_d[2,0])

tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
print(tensor_two_d[2,1:])

tf.Tensor([5 6], shape=(2,), dtype=int32)


In [ ]:
print(tensor_two_d[:,0])

tf.Tensor([1 3 1 2], shape=(4,), dtype=int32)


In [ ]:
print(tensor_two_d[...,0])

tf.Tensor([1 3 1 2], shape=(4,), dtype=int32)


In [ ]:
tensor_three_d=tf.constant([

    [[1,2,0],
     [3,5,-1]],

    [[10,2,0],
     [5,4,3]],

    [[6,2,7],
     [2,7,4]],

    [[1,2,3],
     [5,6,7]]

])
print(tensor_three_d[0,:,:])

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32)


In [ ]:
print(tensor_three_d[0,:,-1])

tf.Tensor([ 0 -1], shape=(2,), dtype=int32)


In [ ]:
print(tensor_three_d[0:2,:,2])

tf.Tensor(
[[ 0 -1]
 [ 0  3]], shape=(2, 2), dtype=int32)


In [ ]:
print(tensor_three_d[...,:,2])

tf.Tensor(
[[ 0 -1]
 [ 0  3]
 [ 7  4]
 [ 3  7]], shape=(4, 2), dtype=int32)


In [ ]:
# absolute value
x_abs = tf.constant ([-2.25,3.25])
tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [ ]:
tf.abs(tf.constant(0.2))

<tf.Tensor: shape=(), dtype=float32, numpy=0.20000000298023224>

In [ ]:
tf.abs(tf.constant(-0.2))

<tf.Tensor: shape=(), dtype=float32, numpy=0.20000000298023224>

In [ ]:
# absolute values for complex numbers
x_abs_complex = tf.constant([-2.25+4.75j])
tf.abs(x_abs_complex)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.25594901])>

In [ ]:
tf.sqrt ((-2.25)**2 + 4.75**2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.255949020385742>

In [ ]:
x_1 = tf.constant([5,3,6,6,4,6],dtype=tf.int32)
x_2 = tf.constant([7,6,2,6,7,11],dtype=tf.int32)
print (tf.add(x_1 , x_2))

tf.Tensor([12  9  8 12 11 17], shape=(6,), dtype=int32)


In [ ]:
x_1 = tf.constant([5,3,6,6,4,6],dtype=tf.int32)
x_2 = tf.constant([7,6,2,6,7,11],dtype=tf.int32)
print (tf.multiply(x_1 , x_2))

tf.Tensor([35 18 12 36 28 66], shape=(6,), dtype=int32)


In [ ]:
x_1 = tf.constant([5,3,6,6,4,6],dtype=tf.int32)
x_2 = tf.constant([7,6,2,6,7,11],dtype=tf.int32)
print (tf.subtract(x_1 , x_2))

tf.Tensor([-2 -3  4  0 -3 -5], shape=(6,), dtype=int32)


In [ ]:
x_1 = tf.constant([5,3,6,6,4,6],dtype=tf.int32)
x_2 = tf.constant([7,6,2,6,7,11],dtype=tf.int32)
print (tf.divide(x_1 , x_2))

tf.Tensor([0.71428571 0.5        3.         1.         0.57142857 0.54545455], shape=(6,), dtype=float64)


In [ ]:
x_1 = tf.constant([5,3,6,6,4,6],dtype=tf.int32)
x_2 = tf.constant([7,6,2,6,7,11],dtype=tf.int32)
print (tf.math.divide_no_nan(x_1 , x_2))

tf.Tensor([0.71428571 0.5        3.         1.         0.57142857 0.54545455], shape=(6,), dtype=float64)


In [ ]:
# broadcasting
x_1 = tf.constant([5,3,6,6,4,6],dtype=tf.int32)
x_2 = tf.constant([7],dtype=tf.int32)
print (tf.math.add(x_1 , x_2))

tf.Tensor([12 10 13 13 11 13], shape=(6,), dtype=int32)


In [ ]:
x_1 = tf.constant([5,3,6,6,4,6],dtype=tf.int32)
x_2 = tf.constant([7],dtype=tf.int32)
x_2_stretched = tf.constant([7,7,7,7,7,7])

print (tf.math.add(x_1 , x_2))
print (tf.math.add(x_1 , x_2_stretched))

tf.Tensor([12 10 13 13 11 13], shape=(6,), dtype=int32)
tf.Tensor([12 10 13 13 11 13], shape=(6,), dtype=int32)


In [ ]:
x_1 = tf.constant([[5,3,6,6,4,6],[2,2,2,2,2,2]],dtype=tf.int32)
x_2 = tf.constant([7],dtype=tf.int32)
x_2_stretched = tf.constant([7,7,7,7,7,7])

print (tf.math.add(x_1 , x_2))
print (tf.math.add(x_1 , x_2_stretched))

tf.Tensor(
[[12 10 13 13 11 13]
 [ 9  9  9  9  9  9]], shape=(2, 6), dtype=int32)
tf.Tensor(
[[12 10 13 13 11 13]
 [ 9  9  9  9  9  9]], shape=(2, 6), dtype=int32)


In [ ]:
x_1 = tf.constant ([[5,3,6,6,4,6],], dtype=tf.float32)
x_2 = tf.constant ([[7],[5],[3]], dtype = tf.float32)

print(x_1.shape)
print(x_2.shape)

print(tf.math.multiply(x_1,x_2))

(1, 6)
(3, 1)
tf.Tensor(
[[35. 21. 42. 42. 28. 42.]
 [25. 15. 30. 30. 20. 30.]
 [15.  9. 18. 18. 12. 18.]], shape=(3, 6), dtype=float32)


In [ ]:
x_argmax=tf.constant([[2,20,30,3,6],
                      [3,11,16,1,8],
                      [14,45,23,5,27]])

print (x_argmax.shape)

(3, 5)


In [ ]:
# index of max val
x_argmax=tf.constant ([200,120,300,300,6])
print (tf.math.argmax(x_argmax))

tf.Tensor(2, shape=(), dtype=int64)


In [ ]:
# index of miv val
x_argmax=tf.constant ([200,120,300,300,6])
print (tf.math.argmin(x_argmax))

tf.Tensor(4, shape=(), dtype=int64)


In [3]:
x=tf.constant([[2,2],[3,3]])
y=tf.constant([[3,0],[1,4]])
tf.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 8,  1],
       [ 3, 81]], dtype=int32)>

In [4]:
tf.pow(tf.constant(2),tf.constant(3))

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [9]:
#sum of all elements
tensor_two_d=tf.constant([[1,2,0],
                          [3,5,-1],
                          [1,5,6],
                          [2,3,8]])
print(tensor_two_d.shape)
print(tf.math.reduce_sum(tensor_two_d,axis=None,keepdims=False,name=None))

(4, 3)
tf.Tensor(35, shape=(), dtype=int32)


In [10]:
print(tf.math.reduce_max(tensor_two_d,axis=None,keepdims=False,name=None))

tf.Tensor(8, shape=(), dtype=int32)


In [11]:
print(tf.math.reduce_min(tensor_two_d,axis=None,keepdims=False,name=None))

tf.Tensor(-1, shape=(), dtype=int32)


In [12]:
#sum of columns
tensor_two_d=tf.constant([[1,2,0],
                          [3,5,-1],
                          [1,5,6],
                          [2,3,8]])
print(tensor_two_d.shape)
print(tf.math.reduce_sum(tensor_two_d,axis=0,keepdims=False,name=None))

(4, 3)
tf.Tensor([ 7 15 13], shape=(3,), dtype=int32)


In [13]:
#sum of rows
tensor_two_d=tf.constant([[1,2,0],
                          [3,5,-1],
                          [1,5,6],
                          [2,3,8]])
print(tensor_two_d.shape)
print(tf.math.reduce_sum(tensor_two_d,axis=1,keepdims=False,name=None))

(4, 3)
tf.Tensor([ 3  7 12 13], shape=(4,), dtype=int32)


In [16]:
tensor_two_d=tf.constant([[2,2,0],
                          [2,5,-1],
                          [2,5,6],
                          [2,3,8]])
print(tensor_two_d.shape)
print(tf.math.reduce_mean(tensor_two_d,axis=0,keepdims=False,name=None))

(4, 3)
tf.Tensor([2 3 3], shape=(3,), dtype=int32)


In [18]:
tensor_two_d=tf.constant([[2,2,0],
                          [2,5,-1],
                          [2,5,6],
                          [2,3,8]], dtype= tf.float16)
print(tensor_two_d.shape)
print(tf.math.reduce_mean(tensor_two_d,axis=0,keepdims=False,name=None))

(4, 3)
tf.Tensor([2.   3.75 3.25], shape=(3,), dtype=float16)


In [19]:
print(tf.math.reduce_std(tensor_two_d,axis=0,keepdims=False,name=None))

tf.Tensor([0.    1.299 3.832], shape=(3,), dtype=float16)


In [20]:
#top val
tf.math.top_k(tensor_two_d,k=1)

TopKV2(values=<tf.Tensor: shape=(4, 1), dtype=float16, numpy=
array([[2.],
       [5.],
       [6.],
       [8.]], dtype=float16)>, indices=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[0],
       [1],
       [2],
       [2]], dtype=int32)>)

In [21]:
# 2 top val
tf.math.top_k(tensor_two_d,k=2)

TopKV2(values=<tf.Tensor: shape=(4, 2), dtype=float16, numpy=
array([[2., 2.],
       [5., 2.],
       [6., 5.],
       [8., 3.]], dtype=float16)>, indices=<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 0],
       [2, 1],
       [2, 1]], dtype=int32)>)

In [22]:
#columns of first matrix must be equal to the rows of second matrix
x_1 = tf.constant ([[1,2,0],
                    [3,5,-1]])
x_2 = tf.constant ([[1,2,0,2],
                    [3,5,-1,2],
                    [4,5,6,0]])

tf.linalg.matmul(
x_1,x_2,transpose_a=False,transpose_b=False, adjoint_a=False, adjoint_b=False,
a_is_sparse=False, b_is_sparse=False, output_type=None)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[  7,  12,  -2,   6],
       [ 14,  26, -11,  16]], dtype=int32)>

In [23]:
print(x_1@x_2)

tf.Tensor(
[[  7  12  -2   6]
 [ 14  26 -11  16]], shape=(2, 4), dtype=int32)


In [24]:
tf.transpose(x_1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  3],
       [ 2,  5],
       [ 0, -1]], dtype=int32)>

In [25]:
tf.transpose(x_2)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  3,  4],
       [ 2,  5,  5],
       [ 0, -1,  6],
       [ 2,  2,  0]], dtype=int32)>

In [30]:
#transpose_b=True => multiply with transpose of the second matrix

x_1= tf.constant ([[1,2,0]])

x_2= tf.constant ([[1,2],
                  [3,5],
                  [4,5]])

x_3=tf.constant ([[1,2,0,2],
                 [3,5,-1,2]])

print(x_1.shape, x_2.shape, x_3.shape, tf.transpose(x_2).shape)

(1, 3) (3, 2) (2, 4) (2, 3)


In [29]:
print(tf.transpose(x_3)@tf.transpose(x_2))

tf.Tensor(
[[ 7 18 19]
 [12 31 33]
 [-2 -5 -5]
 [ 6 16 18]], shape=(4, 3), dtype=int32)


In [32]:
x_1 = tf.constant([[[1,2],
                    [3,5]],
                   [[10,0],
                    [1,2]],
                   [[5,0],
                    [2,0]]])

x_2 = tf.constant([[[5,1,4],
                    [34,15,1]],
                   [[1,2,2],
                    [5,3,2]],
                   [[2,2,3],
                    [1,1,1]]])

print(tf.linalg.matmul(x_1, x_2))

tf.Tensor(
[[[ 73  31   6]
  [185  78  17]]

 [[ 10  20  20]
  [ 11   8   6]]

 [[ 10  10  15]
  [  4   4   6]]], shape=(3, 2, 3), dtype=int32)


In [35]:
x_1 = tf.constant([[[10,0],
                    [1,2]]])

x_2 = tf.constant([
                   [[1,2,2],
                    [5,3,2]],
                  ])

print(tf.linalg.matmul(x_1, x_2))

tf.Tensor(
[[[10 20 20]
  [11  8  6]]], shape=(1, 2, 3), dtype=int32)


In [36]:
x_1 = tf.constant([[[0,0],
                    [0,2]]])

x_2 = tf.constant([
                   [[1,0,0],
                    [0,0,0]],
                  ])

print(tf.linalg.matmul(x_1, x_2))

tf.Tensor(
[[[0 0 0]
  [0 0 0]]], shape=(1, 2, 3), dtype=int32)


In [38]:
tensor_two_d=tf.constant([[1,-2,0],
                          [3,5,100],
                          [1,5,6],
                          [2,3,8]],dtype=tf.float16)

tf.linalg.band_part(tensor_two_d,0,0)

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 6.],
       [0., 0., 0.]], dtype=float16)>

In [40]:
tensor_two_d=tf.constant([[1,-2,0],
                          [3,5,100],
                          [1,5,6],
                          [2,3,8]],dtype=tf.float16)

tensor_out_d=tf.constant([[1,0,0],
                          [0,5,0],
                          [0,0,6],
                          [0,0,0]],dtype=tf.float16)


tf.linalg.band_part(tensor_two_d,0,0)

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 6.],
       [0., 0., 0.]], dtype=float16)>

In [42]:
tensor_two_d=tf.constant([[1,-2,0],
                          [3,5,100],
                          [1,5,6],
                          [2,3,8]],dtype=tf.float16)

tensor_out_d=tf.constant([[1,0,0],
                          [0,5,0],
                          [0,0,6],
                          [0,0,0]],dtype=tf.float16)


tf.linalg.band_part(tensor_two_d,-1,0)

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[1., 0., 0.],
       [3., 5., 0.],
       [1., 5., 6.],
       [2., 3., 8.]], dtype=float16)>

In [43]:
tensor_two_d=tf.constant([[1,-2,0],
                          [3,5,100],
                          [1,5,6],
                          [2,3,8]],dtype=tf.float16)

tensor_out_d=tf.constant([[1,0,0],
                          [0,5,0],
                          [0,0,6],
                          [0,0,0]],dtype=tf.float16)


tf.linalg.band_part(tensor_two_d,0,-1)

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[  1.,  -2.,   0.],
       [  0.,   5., 100.],
       [  0.,   0.,   6.],
       [  0.,   0.,   0.]], dtype=float16)>

In [45]:
tensor_two_d_m_n=tf.constant([[0,-1,-2],
                              [1,0,-1],
                              [2,1,0],
                              [3,2,1]],dtype=tf.float16)

tensor_out_d_n_m=tf.constant([[0,1,2],
                              [-1,0,1],
                              [-2,-1,0],
                              [-3,-2,-1]],dtype=tf.float16)

In [47]:
tensor_two_d=tf.constant([[1,-2,0],
                          [3,5,100],
                          [1,5,6]],dtype=tf.float32)

tf.linalg.inv(tensor_two_d)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.7413249 , -0.01892742,  0.3154574 ],
       [-0.12933755, -0.00946371,  0.1577287 ],
       [-0.01577287,  0.01104101, -0.01735016]], dtype=float32)>

In [46]:
tensor_two_d=tf.constant([[1,-2,0],
                          [3,5,100],
                          [1,5,6]],dtype=tf.float32)

tensor_two_d_inv=tf.linalg.inv(tensor_two_d)

In [48]:
tensor_two_d@tensor_two_d_inv

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.0000000e+00,  7.4505806e-09,  0.0000000e+00],
       [ 1.6391277e-07,  1.0000000e+00,  4.4703484e-08],
       [-5.2154064e-08,  7.4505806e-08,  1.0000000e+00]], dtype=float32)>